version: "3.9"

services:
  app:
    build: .
    environment:
      DB_HOST: db # Use the service name 'db' to connect to the PostgreSQL container
      DB_PORT: 5432
      DB_NAME: plotdbserver
      DB_USER: plot_db_user
      DB_PASSWORD: dkTHrjiCn5DS
      NODE_OPTIONS: --max-old-space-size=4096

    ports:
      - "5500:5500"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: plot_db_user
      POSTGRES_PASSWORD: dkTHrjiCn5DS
      POSTGRES_DB: plotdbserver
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
